### PR TITLE
EBay question LargestSumContiguousSubarray

### PR DESCRIPTION
**Pull request by KetanA**
@aashish-pathak :
please review

### CODE REVIEW

**Comment by KetanA** [comment]
@aashish-pathak @vivekrsharma 
Please review and merge.
Sorry for flooding in same PR.  Will take care onwards.

**Comment by aashish-pathak** [comment]
I agree, we should not over do it. Have at least two test cases. The examples we write as part of problem statement should go in the test cases. 2 test cases are more than sufficient.

**Comment by aashish-pathak** [comment]
I have done my part of review. Should I go ahead and merge this PR? Waiting for Vivek's reply.

**Comment by vivekrsharma** [comment]
Sorry,  this got slacked on my part. I'll finish the review today.

**Pull request merged**
